CREATE TABLE IF NOT EXISTS link_visit (id BIGSERIAL PRIMARY KEY, host_id uuid NOT NULL, url TEXT NOT NULL, outcome VARCHAR(32) NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_link_visit_host_id__id FOREIGN KEY (host_id) REFERENCES host(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE SEQUENCE IF NOT EXISTS link_visit_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
ALTER TABLE star ADD published_at TIMESTAMP NULL;
ALTER TABLE star ALTER COLUMN accessed_at TYPE TIMESTAMP, ALTER COLUMN accessed_at DROP NOT NULL;
