ALTER TABLE star ADD visibility REAL NOT NULL;
ALTER TABLE star ADD updated_at TIMESTAMP NOT NULL;
ALTER TABLE star ADD created_at TIMESTAMP NOT NULL;
ALTER TABLE star ADD discovered_at TIMESTAMP NOT NULL;
