CREATE TABLE IF NOT EXISTS star_log (id BIGSERIAL PRIMARY KEY, visibility REAL NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE SEQUENCE IF NOT EXISTS star_log_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
